server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data_local
    username: data_local
    password: data_local


  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


application:
  Environment: local

